### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by z3t0** [WayneBooth/gsimavr#1]
Any particular reason for using GLUT instead of something like Qt?

**Comment by WayneBooth** [comment]
No reason. Not having done a lot of gui work, I'm not really familiar with either option.
I suppose I was expecting the front end to be rather simple, and since simavr already used glut for their examples, it felt right.
However I've reached the limits of glut, so a higher level interface library could well be more appropriate.

**Comment by z3t0** [comment]
Ah I see, thanks for the explanation.
